import Leanix.Schema
import Leanix.Validate

namespace Leanix
namespace Examples

def nixpkgsInput : Input :=
  .flake {
    url := "github:NixOS/nixpkgs/nixos-unstable"
  }

def helloPackage : Package .x86_64_linux where
  name := "hello"
  build := .nixpkgs "hello"

def helloApp : App .x86_64_linux where
  name := "hello"
  packageName := "hello"
  program := "bin/hello"

def helloDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["hello"]

def helloCheck : Check .x86_64_linux where
  name := "hello"
  packageName := "hello"
  command := "hello --version > \"$out\""

def helloOutputs : Outputs where
  packages
    | .x86_64_linux => [helloPackage]
    | _ => []
  apps
    | .x86_64_linux => [helloApp]
    | _ => []
  devShells
    | .x86_64_linux => [helloDevShell]
    | _ => []
  checks
    | .x86_64_linux => [helloCheck]
    | _ => []

def helloFlake : Flake where
  description := "Leanix typed hello flake"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := helloOutputs

def leanixSource (url : String) : Input :=
  .localDevSource url

def leanixPackage : Package .x86_64_linux where
  name := "leanix"
  build := .runSteps "leanix-build" [.nixpkgs "lean4"] [
    .copySource (.inputPath "leanixSrc") "source",
    .buildLeanProject "source",
    .run "touch \"$out\""
  ]

def leanixDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["leanix"]

def leanixCheck : Check .x86_64_linux where
  name := "build"
  packageName := "leanix"
  command := "touch \"$out\""

def selfOutputs : Outputs where
  packages
    | .x86_64_linux => [leanixPackage]
    | _ => []
  apps := fun _ => []
  devShells
    | .x86_64_linux => [leanixDevShell]
    | _ => []
  checks
    | .x86_64_linux => [leanixCheck]
    | _ => []

def selfFlakeWithSource (sourceUrl : String) : Flake where
  description := "Leanix self-check flake generated by Leanix"
  inputs := [
    ("nixpkgs", nixpkgsInput),
    ("leanixSrc", leanixSource sourceUrl)
  ]
  outputs := selfOutputs

def selfFlake : Flake :=
  selfFlakeWithSource "path:.."

def unhashedSourceInput : Input :=
  .source {
    url := "https://example.com/leanix-source.tar.gz"
  }

def unhashedSourceFlake : Flake where
  description := "Leanix invalid unhashed source example"
  inputs := [
    ("nixpkgs", nixpkgsInput),
    ("unhashedSrc", unhashedSourceInput)
  ]
  outputs := helloOutputs

def helloToolPackage : Package .x86_64_linux where
  name := "helloTool"
  build := .nixpkgs "hello"

def helloWrapperPackage : Package .x86_64_linux where
  name := "helloWrapper"
  build := .runSteps "hello-wrapper" [.package "helloTool"] [
    .installExecutableScript "$out/bin/hello-wrapper" (
      "#!/bin/sh\n" ++
      "${self.packages.${system}.helloTool}/bin/hello --version"
    )
  ]

def closureCheck : Check .x86_64_linux where
  name := "helloWrapper"
  packageName := "helloWrapper"
  command := "hello-wrapper > \"$out\""

def closureOutputs : Outputs where
  packages
    | .x86_64_linux => [helloToolPackage, helloWrapperPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks
    | .x86_64_linux => [closureCheck]
    | _ => []

def closureFlake : Flake where
  description := "Leanix typed closure example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := closureOutputs

def closureCheckedPackageGraph : CheckedPackageGraph .x86_64_linux where
  packages := [helloToolPackage, helloWrapperPackage]
  valid := {
    refsResolve := by native_decide
    acyclicByFuel := by native_decide
  }

def missingRefPackage : Package .x86_64_linux where
  name := "broken"
  build := .runCommand "broken" [.package "missing"] "touch \"$out\""

def missingRefOutputs : Outputs where
  packages
    | .x86_64_linux => [missingRefPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def missingRefFlake : Flake where
  description := "Leanix missing package reference example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := missingRefOutputs

def cyclePackageA : Package .x86_64_linux where
  name := "cycleA"
  build := .runCommand "cycle-a" [.package "cycleB"] "touch \"$out\""

def cyclePackageB : Package .x86_64_linux where
  name := "cycleB"
  build := .runCommand "cycle-b" [.package "cycleA"] "touch \"$out\""

def cycleOutputs : Outputs where
  packages
    | .x86_64_linux => [cyclePackageA, cyclePackageB]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def cycleFlake : Flake where
  description := "Leanix cyclic package reference example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := cycleOutputs

def escapingPackageName : String :=
  "escape\"pkg\\''"

def escapingPackage : Package .x86_64_linux where
  name := escapingPackageName
  build := .runSteps "escape\"builder\\''" [] [
    .mkdir "$out/bin",
    .writeFile "$out/bin/escape-check" (
      "#!/bin/sh\n" ++
      "cat <<'END'\n" ++
      "literal '' in generated content\n" ++
      "EOF\n" ++
      "quote \" and slash \\\n" ++
      "END\n"
    ),
    .chmodExecutable "$out/bin/escape-check"
  ]

def escapingCheck : Check .x86_64_linux where
  name := "escape\"check\\''"
  packageName := escapingPackageName
  command := "escape-check > \"$out\""

def escapingOutputs : Outputs where
  packages
    | .x86_64_linux => [escapingPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks
    | .x86_64_linux => [escapingCheck]
    | _ => []

def escapingFlake : Flake where
  description := "Leanix renderer escaping example \" \\ ''"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := escapingOutputs

def multiLinuxPackage : Package .x86_64_linux where
  name := "hello"
  build := .nixpkgs "hello"

def multiAarch64Package : Package .aarch64_linux where
  name := "hello"
  build := .nixpkgs "hello"

def multiSystemOutputs : Outputs where
  packages
    | .x86_64_linux => [multiLinuxPackage]
    | .aarch64_linux => [multiAarch64Package]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def multiSystemFlake : Flake where
  description := "Leanix multi-system renderer example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := multiSystemOutputs

def helloCliProject : CliProject .x86_64_linux where
  package := helloPackage
  app := { helloApp with name := "default" }
  devShell := helloDevShell
  check := { helloCheck with name := "default" }

def helloCliValidatedSchema : Except SchemaError (ValidatedSchema (CliProject .x86_64_linux)) :=
  CliProject.validateChecked helloCliProject

def helloCliSchemaFlake : Except String ValidatedFlake := do
  let validated ←
    match helloCliValidatedSchema with
    | .ok validated => pure validated
    | .error error => throw error.toString
  match Flake.fromValidatedSchema "Leanix typed CLI schema example" [("nixpkgs", nixpkgsInput)] validated with
  | .ok validatedFlake => pure validatedFlake
  | .error error => throw error.toString

def brokenCliProject : CliProject .x86_64_linux where
  package := helloPackage
  app := { helloApp with name := "default", packageName := "missing" }
  devShell := helloDevShell
  check := { helloCheck with name := "default" }

def brokenCliSchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix invalid CLI schema example" [("nixpkgs", nixpkgsInput)] brokenCliProject

def showcaseCliProject : CliProject .x86_64_linux where
  package := helloWrapperPackage
  extraPackages := [helloToolPackage]
  app := {
    name := "default"
    packageName := "helloWrapper"
    program := "bin/hello-wrapper"
  }
  devShell := {
    name := "default"
    packageNames := ["helloWrapper"]
  }
  check := {
    name := "default"
    packageName := "helloWrapper"
    command := "hello-wrapper > \"$out\""
  }

def showcaseValidatedSchema : Except SchemaError (ValidatedSchema (CliProject .x86_64_linux)) :=
  CliProject.validateChecked showcaseCliProject

def showcaseFlake : Except String ValidatedFlake := do
  let validated ←
    match showcaseValidatedSchema with
    | .ok validated => pure validated
    | .error error => throw error.toString
  match Flake.fromValidatedSchema "Leanix proof-carrying CLI closure showcase" [("nixpkgs", nixpkgsInput)] validated with
  | .ok validatedFlake => pure validatedFlake
  | .error error => throw error.toString

end Examples
end Leanix
