import Leanix.Core

namespace Leanix
namespace Examples

def nixpkgsInput : Input :=
  .flake {
    url := "github:NixOS/nixpkgs/nixos-unstable"
  }

def helloPackage : Package .x86_64_linux where
  name := "hello"
  build := .nixpkgs "hello"

def helloApp : App .x86_64_linux where
  name := "hello"
  packageName := "hello"
  program := "bin/hello"

def helloDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["hello"]

def helloCheck : Check .x86_64_linux where
  name := "hello"
  packageName := "hello"
  command := "hello --version > \"$out\""

def helloOutputs : Outputs where
  packages
    | .x86_64_linux => [helloPackage]
    | _ => []
  apps
    | .x86_64_linux => [helloApp]
    | _ => []
  devShells
    | .x86_64_linux => [helloDevShell]
    | _ => []
  checks
    | .x86_64_linux => [helloCheck]
    | _ => []

def helloFlake : Flake where
  description := "Leanix typed hello flake"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := helloOutputs

def leanixSource (url : String) : Input :=
  .localSource url

def leanixBuildScript : String :=
  "cp -R ${leanixSrc} source\n" ++
  "chmod -R u+w source\n" ++
  "cd source\n" ++
  "lake build\n" ++
  "touch \"$out\""

def leanixPackage : Package .x86_64_linux where
  name := "leanix"
  build := .runCommand "leanix-build" [.nixpkgs "lean4"] leanixBuildScript

def leanixDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["leanix"]

def leanixCheck : Check .x86_64_linux where
  name := "build"
  packageName := "leanix"
  command := "touch \"$out\""

def selfOutputs : Outputs where
  packages
    | .x86_64_linux => [leanixPackage]
    | _ => []
  apps := fun _ => []
  devShells
    | .x86_64_linux => [leanixDevShell]
    | _ => []
  checks
    | .x86_64_linux => [leanixCheck]
    | _ => []

def selfFlakeWithSource (sourceUrl : String) : Flake where
  description := "Leanix self-check flake generated by Leanix"
  inputs := [
    ("nixpkgs", nixpkgsInput),
    ("leanixSrc", leanixSource sourceUrl)
  ]
  outputs := selfOutputs

def selfFlake : Flake :=
  selfFlakeWithSource "path:.."

end Examples
end Leanix
