import Leanix.Schema
import Leanix.Validate

namespace Leanix
namespace Examples

def nixpkgsInput : Input :=
  .flake {
    url := "github:NixOS/nixpkgs/nixos-unstable"
  }

def pinnedNixpkgsInput : Input :=
  .flake {
    url := "github:NixOS/nixpkgs/nixos-unstable"
    rev? := some "549bd84d6279f9852cae6225e372cc67fb91a4c1"
    narHash? := some {
      algorithm := .sha256
      digest := "hGdgeU2Nk87RAuZyYjyDjFL6LK7dAZN5RE9+hrDTkDU="
    }
  }

def helloPackage : Package .x86_64_linux where
  name := "hello"
  build := .nixpkgs "hello"

def helloApp : App .x86_64_linux where
  name := "hello"
  packageName := "hello"
  program := "bin/hello"

def helloDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["hello"]

def helloCheck : Check .x86_64_linux where
  name := "hello"
  packageName := "hello"
  command := "hello --version > \"$out\""

def helloOutputs : Outputs where
  packages
    | .x86_64_linux => [helloPackage]
    | _ => []
  apps
    | .x86_64_linux => [helloApp]
    | _ => []
  devShells
    | .x86_64_linux => [helloDevShell]
    | _ => []
  checks
    | .x86_64_linux => [helloCheck]
    | _ => []

def helloFlake : Flake where
  description := "Leanix typed hello flake"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := helloOutputs

def leanixSource (url : String) : Input :=
  .localDevSource url

def leanixPackage : Package .x86_64_linux where
  name := "leanix"
  build := .runSteps "leanix-build" [.nixpkgs "lean4"] [
    .copySource (.inputPath "leanixSrc") "source",
    .buildLeanProject "source",
    .run "touch \"$out\""
  ]

def leanixDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["leanix"]

def leanixCheck : Check .x86_64_linux where
  name := "build"
  packageName := "leanix"
  command := "touch \"$out\""

def selfOutputs : Outputs where
  packages
    | .x86_64_linux => [leanixPackage]
    | _ => []
  apps := fun _ => []
  devShells
    | .x86_64_linux => [leanixDevShell]
    | _ => []
  checks
    | .x86_64_linux => [leanixCheck]
    | _ => []

def selfFlakeWithSource (sourceUrl : String) : Flake where
  description := "Leanix self-check flake generated by Leanix"
  inputs := [
    ("nixpkgs", nixpkgsInput),
    ("leanixSrc", leanixSource sourceUrl)
  ]
  outputs := selfOutputs

def selfFlake : Flake :=
  selfFlakeWithSource "path:.."

def unhashedSourceInput : Input :=
  .source {
    url := "https://example.com/leanix-source.tar.gz"
  }

def unhashedSourceFlake : Flake where
  description := "Leanix invalid unhashed source example"
  inputs := [
    ("nixpkgs", nixpkgsInput),
    ("unhashedSrc", unhashedSourceInput)
  ]
  outputs := helloOutputs

def hashedSourceInput (url : String) : Input :=
  .source {
    url := url
    narHash? := some {
      algorithm := .sha256
      digest := "jsgXtBABq0OCdKEeY0mS7yzxEAn4GAJgw7zldbIgGGw="
    }
  }

def sourceFixturePackage : Package .x86_64_linux where
  name := "sourceFixture"
  build := .runSteps "source-fixture" [] [
    .copySource (.inputPath "fixtureSrc") "source",
    .mkdir "$out",
    .run "cp source/message.txt \"$out/message.txt\""
  ]

def sourceFixtureCheck : Check .x86_64_linux where
  name := "sourceFixture"
  packageName := "sourceFixture"
  command := "touch \"$out\""

def sourceFixtureOutputs : Outputs where
  packages
    | .x86_64_linux => [sourceFixturePackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks
    | .x86_64_linux => [sourceFixtureCheck]
    | _ => []

def sourceFixtureFlakeWithSource (sourceUrl : String) : Flake where
  description := "Leanix hashed source input example"
  inputs := [
    ("nixpkgs", nixpkgsInput),
    ("fixtureSrc", hashedSourceInput sourceUrl)
  ]
  outputs := sourceFixtureOutputs

def sourceFixtureFlake : Flake :=
  sourceFixtureFlakeWithSource "path:../e2e/source-fixture"

def envPackage : Package .x86_64_linux where
  name := "envEcho"
  env := [
    { name := "LEANIX_MESSAGE", value := "hello from Leanix env" }
  ]
  build := .runCommand "env-echo" [] (
    "test \"$LEANIX_MESSAGE\" = \"hello from Leanix env\"\n" ++
    "mkdir -p \"$out\"\n" ++
    "printf \"%s\\n\" \"$LEANIX_MESSAGE\" > \"$out/message\""
  )

def envDevShell : DevShell .x86_64_linux where
  name := "env"
  packageNames := ["envEcho"]
  env := [
    { name := "LEANIX_MESSAGE", value := "hello from Leanix shell" }
  ]

def envCheck : Check .x86_64_linux where
  name := "envEcho"
  packageName := "envEcho"
  command := "touch \"$out\""

def envOutputs : Outputs where
  packages
    | .x86_64_linux => [envPackage]
    | _ => []
  apps := fun _ => []
  devShells
    | .x86_64_linux => [envDevShell]
    | _ => []
  checks
    | .x86_64_linux => [envCheck]
    | _ => []

def envFlake : Flake where
  description := "Leanix env var example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := envOutputs

def duplicatePackageEnvPackage : Package .x86_64_linux where
  name := "duplicatePackageEnv"
  env := [
    { name := "LEANIX_DUP", value := "first" },
    { name := "LEANIX_DUP", value := "second" }
  ]
  build := .runCommand "duplicate-package-env" [] "touch \"$out\""

def duplicatePackageEnvOutputs : Outputs where
  packages
    | .x86_64_linux => [duplicatePackageEnvPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def duplicatePackageEnvFlake : Flake where
  description := "Leanix duplicate package env example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := duplicatePackageEnvOutputs

def duplicateShellEnvShell : DevShell .x86_64_linux where
  name := "dupShell"
  packageNames := ["hello"]
  env := [
    { name := "LEANIX_DUP", value := "first" },
    { name := "LEANIX_DUP", value := "second" }
  ]

def duplicateShellEnvOutputs : Outputs where
  packages
    | .x86_64_linux => [helloPackage]
    | _ => []
  apps := fun _ => []
  devShells
    | .x86_64_linux => [duplicateShellEnvShell]
    | _ => []
  checks := fun _ => []

def duplicateShellEnvFlake : Flake where
  description := "Leanix duplicate shell env example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := duplicateShellEnvOutputs

def unsupportedEnvPackage : Package .x86_64_linux where
  name := "unsupportedEnv"
  env := [
    { name := "LEANIX_MESSAGE", value := "not wired through nixpkgs builders" }
  ]
  build := .nixpkgs "hello"

def unsupportedEnvOutputs : Outputs where
  packages
    | .x86_64_linux => [unsupportedEnvPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def unsupportedEnvFlake : Flake where
  description := "Leanix unsupported package env example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := unsupportedEnvOutputs

def pinnedInputFlake : Flake where
  description := "Leanix pinned flake input example"
  inputs := [("nixpkgs", pinnedNixpkgsInput)]
  outputs := helloOutputs

def helloToolPackage : Package .x86_64_linux where
  name := "helloTool"
  build := .nixpkgs "hello"

def helloWrapperPackage : Package .x86_64_linux where
  name := "helloWrapper"
  build := .runSteps "hello-wrapper" [.package "helloTool"] [
    .installExecutableTextScript "$out/bin/hello-wrapper" (
      .concat [
        .literal "#!/bin/sh\n",
        .package "helloTool",
        .literal "/bin/hello --version\n"
      ]
    )
  ]

def closureCheck : Check .x86_64_linux where
  name := "helloWrapper"
  packageName := "helloWrapper"
  command := "hello-wrapper > \"$out\""

def closureOutputs : Outputs where
  packages
    | .x86_64_linux => [helloToolPackage, helloWrapperPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks
    | .x86_64_linux => [closureCheck]
    | _ => []

def closureFlake : Flake where
  description := "Leanix typed closure example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := closureOutputs

def closureCheckedPackageGraph : CheckedPackageGraph .x86_64_linux where
  packages := [helloToolPackage, helloWrapperPackage]
  valid := {
    refsResolve := by native_decide
    acyclicByFuel := by native_decide
  }

def missingRefPackage : Package .x86_64_linux where
  name := "broken"
  build := .runCommand "broken" [.package "missing"] "touch \"$out\""

def missingRefOutputs : Outputs where
  packages
    | .x86_64_linux => [missingRefPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def missingRefFlake : Flake where
  description := "Leanix missing package reference example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := missingRefOutputs

def typedTextMissingRefPackage : Package .x86_64_linux where
  name := "typedTextBroken"
  build := .runSteps "typed-text-broken" [] [
    .installExecutableTextScript "$out/bin/broken" (
      .concat [
        .literal "#!/bin/sh\n",
        .package "missingTextDep",
        .literal "/bin/missing\n"
      ]
    )
  ]

def typedTextMissingRefOutputs : Outputs where
  packages
    | .x86_64_linux => [typedTextMissingRefPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def typedTextMissingRefFlake : Flake where
  description := "Leanix typed build text missing package reference example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := typedTextMissingRefOutputs

def cyclePackageA : Package .x86_64_linux where
  name := "cycleA"
  build := .runCommand "cycle-a" [.package "cycleB"] "touch \"$out\""

def cyclePackageB : Package .x86_64_linux where
  name := "cycleB"
  build := .runCommand "cycle-b" [.package "cycleA"] "touch \"$out\""

def cycleOutputs : Outputs where
  packages
    | .x86_64_linux => [cyclePackageA, cyclePackageB]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def cycleFlake : Flake where
  description := "Leanix cyclic package reference example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := cycleOutputs

def escapingPackageName : String :=
  "escape\"pkg\\''"

def escapingPackage : Package .x86_64_linux where
  name := escapingPackageName
  build := .runSteps "escape\"builder\\''" [] [
    .mkdir "$out/bin",
    .writeFile "$out/bin/escape-check" (
      "#!/bin/sh\n" ++
      "cat <<'END'\n" ++
      "literal '' in generated content\n" ++
      "EOF\n" ++
      "quote \" and slash \\\n" ++
      "END\n"
    ),
    .chmodExecutable "$out/bin/escape-check"
  ]

def escapingCheck : Check .x86_64_linux where
  name := "escape\"check\\''"
  packageName := escapingPackageName
  command := "escape-check > \"$out\""

def escapingOutputs : Outputs where
  packages
    | .x86_64_linux => [escapingPackage]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks
    | .x86_64_linux => [escapingCheck]
    | _ => []

def escapingFlake : Flake where
  description := "Leanix renderer escaping example \" \\ ''"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := escapingOutputs

def multiLinuxPackage : Package .x86_64_linux where
  name := "hello"
  build := .nixpkgs "hello"

def multiAarch64Package : Package .aarch64_linux where
  name := "hello"
  build := .nixpkgs "hello"

def multiSystemOutputs : Outputs where
  packages
    | .x86_64_linux => [multiLinuxPackage]
    | .aarch64_linux => [multiAarch64Package]
    | _ => []
  apps := fun _ => []
  devShells := fun _ => []
  checks := fun _ => []

def multiSystemFlake : Flake where
  description := "Leanix multi-system renderer example"
  inputs := [("nixpkgs", nixpkgsInput)]
  outputs := multiSystemOutputs

def multiLinuxApp : App .x86_64_linux where
  name := "default"
  packageName := "hello"
  program := "bin/hello"

def multiAarch64App : App .aarch64_linux where
  name := "default"
  packageName := "hello"
  program := "bin/hello"

def multiLinuxDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["hello"]

def multiAarch64DevShell : DevShell .aarch64_linux where
  name := "default"
  packageNames := ["hello"]

def multiLinuxCheck : Check .x86_64_linux where
  name := "default"
  packageName := "hello"
  command := "hello --version > \"$out\""

def multiAarch64Check : Check .aarch64_linux where
  name := "default"
  packageName := "hello"
  command := "hello --version > \"$out\""

def multiLinuxCliProject : CliProject .x86_64_linux where
  package := multiLinuxPackage
  app := multiLinuxApp
  devShell := multiLinuxDevShell
  check := multiLinuxCheck

def multiAarch64CliProject : CliProject .aarch64_linux where
  package := multiAarch64Package
  app := multiAarch64App
  devShell := multiAarch64DevShell
  check := multiAarch64Check

def multiSystemCliProject : MultiSystemCliProject where
  name := "hello"
  x86_64Linux := some multiLinuxCliProject
  aarch64Linux := some multiAarch64CliProject

def multiSystemSchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix multi-system CLI schema example" [("nixpkgs", nixpkgsInput)]
    multiSystemCliProject

def brokenMultiAarch64CliProject : CliProject .aarch64_linux where
  package := multiAarch64Package
  app := { multiAarch64App with packageName := "missing" }
  devShell := multiAarch64DevShell
  check := multiAarch64Check

def brokenMultiSystemCliProject : MultiSystemCliProject where
  name := "broken"
  x86_64Linux := some multiLinuxCliProject
  aarch64Linux := some brokenMultiAarch64CliProject

def brokenMultiSystemSchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix invalid multi-system CLI schema example" [("nixpkgs", nixpkgsInput)]
    brokenMultiSystemCliProject

def helloCliProject : CliProject .x86_64_linux where
  package := helloPackage
  app := { helloApp with name := "default" }
  devShell := helloDevShell
  check := { helloCheck with name := "default" }

def helloCliValidatedSchema : Except SchemaError (ValidatedSchema (CliProject .x86_64_linux)) :=
  CliProject.validateChecked helloCliProject

def helloCliSchemaFlake : Except String ValidatedFlake := do
  let validated ←
    match helloCliValidatedSchema with
    | .ok validated => pure validated
    | .error error => throw error.toString
  match Flake.fromValidatedSchema "Leanix typed CLI schema example" [("nixpkgs", nixpkgsInput)] validated with
  | .ok validatedFlake => pure validatedFlake
  | .error error => throw error.toString

def brokenCliProject : CliProject .x86_64_linux where
  package := helloPackage
  app := { helloApp with name := "default", packageName := "missing" }
  devShell := helloDevShell
  check := { helloCheck with name := "default" }

def brokenCliSchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix invalid CLI schema example" [("nixpkgs", nixpkgsInput)] brokenCliProject

def showcaseCliProject : CliProject .x86_64_linux where
  package := helloWrapperPackage
  extraPackages := [helloToolPackage]
  app := {
    name := "default"
    packageName := "helloWrapper"
    program := "bin/hello-wrapper"
  }
  devShell := {
    name := "default"
    packageNames := ["helloWrapper"]
  }
  check := {
    name := "default"
    packageName := "helloWrapper"
    command := "hello-wrapper > \"$out\""
  }

def showcaseValidatedSchema : Except SchemaError (ValidatedSchema (CliProject .x86_64_linux)) :=
  CliProject.validateChecked showcaseCliProject

def showcaseFlake : Except String ValidatedFlake := do
  let validated ←
    match showcaseValidatedSchema with
    | .ok validated => pure validated
    | .error error => throw error.toString
  match Flake.fromValidatedSchema "Leanix proof-carrying CLI closure showcase" [("nixpkgs", nixpkgsInput)] validated with
  | .ok validatedFlake => pure validatedFlake
  | .error error => throw error.toString

def libraryPackage : Package .x86_64_linux where
  name := "helloLib"
  build := .nixpkgs "hello"

def libraryDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["helloLib"]

def libraryCheck : Check .x86_64_linux where
  name := "default"
  packageName := "helloLib"
  command := "hello --version > \"$out\""

def libraryProject : LibraryProject .x86_64_linux where
  package := libraryPackage
  devShell := libraryDevShell
  check := libraryCheck

def librarySchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix library schema example" [("nixpkgs", nixpkgsInput)]
    libraryProject

def brokenLibraryProject : LibraryProject .x86_64_linux where
  package := libraryPackage
  devShell := { libraryDevShell with name := "dev" }
  check := libraryCheck

def brokenLibrarySchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix invalid library schema example" [("nixpkgs", nixpkgsInput)]
    brokenLibraryProject

def multiAppHelloApp : App .x86_64_linux where
  name := "hello"
  packageName := "helloTool"
  program := "bin/hello"

def multiAppWrapperApp : App .x86_64_linux where
  name := "wrapper"
  packageName := "helloWrapper"
  program := "bin/hello-wrapper"

def multiAppDevShell : DevShell .x86_64_linux where
  name := "default"
  packageNames := ["helloTool", "helloWrapper"]

def multiAppCheck : Check .x86_64_linux where
  name := "wrapper"
  packageName := "helloWrapper"
  command := "hello-wrapper > \"$out\""

def multiAppProject : MultiAppProject .x86_64_linux where
  packages := [helloToolPackage, helloWrapperPackage]
  apps := [multiAppHelloApp, multiAppWrapperApp]
  devShells := [multiAppDevShell]
  checks := [multiAppCheck]

def multiAppSchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix multi-app schema example" [("nixpkgs", nixpkgsInput)]
    multiAppProject

def brokenMultiAppProject : MultiAppProject .x86_64_linux where
  packages := [helloToolPackage, helloWrapperPackage]
  apps := [multiAppHelloApp]
  devShells := [multiAppDevShell]
  checks := [multiAppCheck]

def brokenMultiAppSchemaFlake : Except String ValidatedFlake :=
  Flake.fromSchema "Leanix invalid multi-app schema example" [("nixpkgs", nixpkgsInput)]
    brokenMultiAppProject

end Examples
end Leanix
